Name:           perl-ex-monkeypatched
Version:        0.03
Release:        1%{?dist}
Summary:        Experimental API for safe monkey-patching
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/ex-monkeypatched/
Source0:        http://www.cpan.org/authors/id/A/AR/ARC/ex-monkeypatched-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Sub::Name)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More) >= 0.88
Requires:       perl(Sub::Name)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
ex::monkeypatched injects methods when you use it. There are two ways to
invoke it with use: one is easy but inflexible, and the other is more
flexible but also more awkward.

%prep
%setup -q -n ex-monkeypatched-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jun 30 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.03-1
- Specfile autogenerated by cpanspec 1.78.
